### Aim: To implement Bag of Words model for document/sentences analysis

In [1]:
# import statments
import numpy
import re
import nltk 
nltk.download('stopwords')
from nltk.corpus import stopwords 
stop_words = set(stopwords.words('english'))
def word_extraction(sentence):
    words = re.sub("[^\w]", " ",  sentence).split()
    cleaned_text = [w.lower() for w in words if w not in stop_words]
    return cleaned_text    

allsentences = ["Joe waited for the train", "The train was late", "Mary and Samantha took the bus", 
            "I looked for Mary and Samantha at the bus station", 
            "Mary and Samantha arrived at the bus station early but waited until noon for the bus"]

def cleaning(allsentences):
      clean_sen = []
      for sentence in allsentences:
        words = word_extraction(sentence)
        clean_sen.append(' '.join(words))
      return clean_sen

from sklearn.feature_extraction.text import CountVectorizer

updated_sen = cleaning(allsentences)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [2]:
updated_sen

['joe waited train',
 'the train late',
 'mary samantha took bus',
 'i looked mary samantha bus station',
 'mary samantha arrived bus station early waited noon bus']

In [3]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(updated_sen)
print(X.toarray())

[[0 0 0 1 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 0 0 0 1 0 1 0]
 [0 1 0 0 0 0 1 0 1 0 0 1 0 0]
 [0 1 0 0 0 1 1 0 1 1 0 0 0 0]
 [1 2 1 0 0 0 1 1 1 1 0 0 0 1]]
